### PR TITLE
PHP Coding standards

### PR DESCRIPTION
**Pull request by Pushplaybang**
This is a simple reference with links to the PHP coding standards and best practices we'd like to follow, in time we should add both a "deviations" section and some examples.

@royscheeren @leogopal @Ricus-Rossouw @jeanduplessis @slopboy @Nona-Creative/nonabots

### CODE REVIEW

**Comment by JamesGarethSmith** [comment]
👍 

Looks good. I'm keen to get this merged in.

**Comment by Sntax** [comment]
From what little PHP experience I have - this looks good  👍

**Comment by slopboy** [comment]
👍

**Comment by Pushplaybang** [comment]
Great, realized that we agreed to some amendments / variationas that I'd like to add to the bottom

* 100 char line lenth
* 2 space indentation over 4 space

**Comment by JamesGarethSmith** [comment]
@Pushplaybang 100 chars or 120?

**Comment by SkippyZA** [comment]
my vote would be 120 as it is the standard in most languages

**Comment by Pushplaybang** [comment]
120 it shall be.

**Pull request merged**
